### ISSUE TITLE
tubes Router is broken

### ISSUE THREAD

**Issue by david415** [twisted/tubes#28]
Besides the broken docstring for the Router as reported in #21 the Router also generally appears not to work; or am I missing something simple here?

see my attempt at creating unit tests for Router:
https://github.com/david415/tubes/tree/add_routing_tests.0
https://github.com/david415/tubes/blob/add_routing_tests.0/tubes/test/test_routing.py

When the Router's newRoute() method is called this results in:

```
$ trial tubes.test.test_routing
tubes.test.test_routing
  TestBasicRouter
    test_basic_router ...                                               [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/user/tubes/tubes/test/test_routing.py", line 64, in test_basic_router
    evenOddTube.addRoutes()
  File "/home/user/tubes/tubes/test/test_routing.py", line 41, in addRoutes
    self.evenRoute = self.newRoute()
  File "/home/user/tubes/tubes/routing.py", line 179, in newRoute
    fount = self._out.newFount().flowTo(received)
  File "/home/user/tubes/tubes/fan.py", line 253, in flowTo
    return beginFlowingTo(self, drain)
  File "/home/user/tubes/tubes/kit.py", line 104, in beginFlowingTo
    return drain.flowingFrom(fount)
exceptions.AttributeError: '_Tubule' object has no attribute 'flowingFrom'

tubes.test.test_routing.TestBasicRouter.test_basic_router
-------------------------------------------------------------------------------
Ran 1 tests in 0.018s

FAILED (errors=1)
```

**Comment by glyph** [comment]
Thanks for reporting this; it seems like a pretty [bad brown paper bag bug](http://foldoc.org/brown%20paper%20bag%20bug) :).

**Comment by glyph** [comment]
:pouch: :bug:
