### ISSUE TITLE
 fix flowFountFromEndpoint pause propagation

### ISSUE THREAD

**Issue by david415** [twisted/tubes#40]
Greetings,

tldr;
```
exceptions.AttributeError: _ProtocolPlumbing instance has no attribute 'pauseProducing'
```

We seem to be exercising a bug in flowFountFromEndpoint with our tubes coroutine pipeline and unit test here:

https://github.com/david415/bananaphone/tree/add-tubes.0
https://github.com/david415/bananaphone/blob/56c871e697c9050e85cf4d9fa8df059deb6f4a0a/bananaphone.py#L901-L934
https://github.com/david415/bananaphone/blob/56c871e697c9050e85cf4d9fa8df059deb6f4a0a/test/test_utils.py#L17-L33

```
(virtenv-tubes)user@python-dev1:~/bananaphone$ trial test/test_utils.py
test_utils
  CoCoTubeDrainTests
    test_drain_changeWordSize ... coroutine drain flowing from
coroutine fount flow to
coroutine drain receive
coroutine drain receive
                                         [OK]
  TubeEndpointProxyTests
    test_tube_proxy ... args
['markov', '/usr/share/dict/words', 'words', 'sha1', 2]
                                                [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/user/virtenv-tubes/local/lib/python2.7/site-packages/tubes/protocol.py", line 400, in listening
    listening.impl = _FountImpl(portObject, aFlowFunction, preListen)
  File "/home/user/virtenv-tubes/local/lib/python2.7/site-packages/tubes/protocol.py", line 331, in __init__
    self._pauser = Pauser(portObject.pauseProducing,
exceptions.AttributeError: _ProtocolPlumbing instance has no attribute 'pauseProducing'

test_utils.TubeEndpointProxyTests.test_tube_proxy
-------------------------------------------------------------------------------
Ran 2 tests in 0.035s

FAILED (errors=1, successes=1)
```

**Comment by david415** [comment]
nevermind, i think i was mistaken about this bug...
